version: "2.4"

services:
  rabbitmq:
    image: legalthings/rabbitmq
    networks:
      - lto

  mongo:
    image: "mongo:3"
    ports:
      - 27747:27017
    networks:
      - lto

  api-gateway:
    container_name: api-gateway
    image: legalthings/api-gateway:v0.1.7
    environment:
      - NODE_ENV=production
    ports:
      - "3000:80"
    networks:
      - lto

  legalflow:
    container_name: legalflow
    image: legalthings/workflow-engine:v0.1.3
    environment:
      - APPLICATION_ENV=docker.dev-queue
      - phpmemory_limit=512M
    volumes:
      - ./volumes/workflow-engine:/app/config/local
    networks:
      - lto
    depends_on:
      - mongo

  legalevents:
    container_name: legalevents
    image: legalthings/event-chain:v0.1.2
    environment:
      - APPLICATION_ENV=docker.dev-queue
      - phpmemory_limit=512M
    networks:
      - lto
    depends_on:
      - mongo

  event-queuer:
    container_name: event-queuer
    image: legalthings/event-dispatcher:v0.1.2
    environment:
      - NODE_ENV=lto
    networks:
      - lto
    depends_on:
      - mongo
      - rabbitmq

  event-dispatcher:
    container_name: event-dispatcher
    image: legalthings/event-dispatcher:v0.1.2
    environment:
      - NODE_ENV=lto
    networks:
      - lto
    depends_on:
      - mongo
      - rabbitmq

  public-node:
    container_name: public-node
    image: ltonetwork/public-node
    mem_reservation: 1g
    volumes:
      - ./volumes/public-node:/lto
    ports:
      - 6869:6869
    environment:
      - LTO_NETWORK=TESTNET
    networks:
      - lto

  redis:
    container_name: redis
    image: redis
    volumes:
      - ./volumes/redis:/lto
    ports:
      - 6379:6379
    networks:
      - lto

  graph:
    container_name: graph
    image: redislabs/redisgraph
    volumes:
      - ./volumes/redis-graph:/lto
    ports:
      - 6380:6379
    networks:
      - lto

  indexer:
    container_name: indexer
    image: ltonetwork/indexer
    environment:
      - NODE_ENV=production
      - NODE_URL=http://public-node:6869
      - STORAGE_TYPE=redis
      - REDIS_URL=redis://redis
      - REDIS_GRAPH_HOST=graph
      - REDIS_GRAPH_PORT=6379
      - TRANSACTION_INDEXING=true
      - ASSOCIATION_INDEXING=all
      - IDENTITY_INDEXING=true
      - ANCHOR_INDEXING=all
      - STATS_INDEXING=true
    ports:
      - 80:80
    networks:
      - lto
    depends_on:
      - public-node

networks:
  lto:
    driver: bridge
