version: "3"

services:
  nginx:
    container_name: nginx
    image: ltonetwork/public-node-proxy
    ports:
      - 80:80
    depents_on:
      - indexer
      - public-node
    networks:
      - lto

  indexer:
    container_name: indexer
    image: ltonetwork/indexer
    environment:
      - NODE_ENV=production
      - NODE_URL=http://public-node:6869
      - TRANSACTION_INDEXING=true
      - ASSOCIATION_INDEXING=all
      - IDENTITY_INDEXING=true
      - ANCHOR_INDEXING=all
      - STATS_INDEXING=true
    ports:
      - 80:80
    networks:
      - lto
    depends_on:
      - public-node

  public-node:
    container_name: public-node
    image: ltonetwork/public-node
    mem_limit: 1g
    volumes:
      - ./volumes/public-node:/lto
    ports:
      - 6869:6869
    environment:
      - LTO_NETWORK=TESTNET
    networks:
      - lto

networks:
  lto:
    driver: bridge
