version: "2.4"

services:
  public-node:
    container_name: public-node
    image: ltonetwork/public-node
    mem_reservation: 1g
    volumes:
      - ./volumes/public-node:/lto
    ports:
      - 6863:6863
      - 6868:6868
    environment:
      - LTO_WALLET_SEED=
      - LTO_NETWORK=MAINNET
      
