version: "2.4"

services:
  public-node:
    container_name: public-node
    image: ltonetwork/public-node
    mem_reservation: 1g
    volumes:
      - ./volumes/public-node:/lto
    ports:
      - 6869:6869
    environment:
      - LTO_NETWORK=TESTNET
    networks:
      - lto

  indexer:
    container_name: indexer
    image: ltonetwork/indexer
    environment:
      - NODE_ENV=production
      - NODE_URL=http://public-node:6869
      - ASSOCIATION_INDEXING=true
      - ANCHOR_INDEXING=all
    ports:
      - 80:80
    networks:
      - lto
    depends_on:
      - public-node

networks:
  lto:
    driver: bridge
