version: '3'

services:
  nginx:
    container_name: nginx
    image: ltonetwork/public-node-proxy
    mem_limit: 134217728 # 128mb
    ports:
      - 80:80
    depents_on:
      - indexer
      - public-node
    networks:
      - lto

  indexer:
    container_name: indexer
    image: legalthings/indexer
    mem_limit: 134217728 # 128mb
    environment:
      - NODE_ENV=production
      - NODE_URL=http://public-node:6869
      - TRANSACTION_INDEXING=true
      - ASSOCIATION_INDEXING=all
      - IDENTITY_INDEXING=true
      - ANCHOR_INDEXING=all
      - STATS_INDEXING=true
    ports:
      - 80:80
    depends_on:
      - public-node
    networks:
      - lto

  public-node:
    container_name: public-node
    image: ltonetwork/public-node:v1.4.1
    mem_limit: 134217728 # 128mb
    volumes:
      - /lto/data:/lto
    environment:
      - ENABLE_REST_API=true
      - LTO_NETWORK=TESTNET
    networks:
      - lto

networks:
  lto:
    driver: bridge

