version: "2.4"

services:
  nginx:
    container_name: nginx
    image: ltonetwork/public-node-proxy
    ports:
      - 80:80
    depends_on:
      - indexer
      - public-node
    networks:
      - lto

  redis:
    container_name: redis
    image: redis
    volumes:
      - lto-redis:/lto
    networks:
      - lto

  graph:
    container_name: graph
    image: redislabs/redisgraph
    volumes:
      - lto-graph:/lto
    networks:
      - lto

  public-node:
    container_name: public-node
    image: ltonetwork/public-node
    volumes:
      - lto-data:/lto
    environment:
      - LTO_NETWORK=TESTNET
      - ENABLE_REST_API=true
    networks:
      - lto

  indexer:
    container_name: indexer
    image: ltonetwork/indexer
    volumes:
      - lto-index:/usr/data/lto-index
    environment:
      - NODE_ENV=production
      - NODE_URL=http://public-node:6869
      - STORAGE_TYPE=redis
      - REDIS_URL=redis://redis
      - REDIS_GRAPH_HOST=graph
      - REDIS_GRAPH_PORT=6379
      - TRANSACTION_INDEXING=true
      - ASSOCIATION_INDEXING=all
      - IDENTITY_INDEXING=true
      - ANCHOR_INDEXING=all
      - STATS_INDEXING=true
    depends_on:
      - public-node
      - redis
      - graph
    networks:
      - lto

volumes:
  lto-data:
  lto-redis:
  lto-graph:
  lto-index:

networks:
  lto:
    driver: bridge
