version: "2.4"

services:
  public-node:
    container_name: public-node
    image: ltonetwork/public-node
    volumes:
      - lto-data:/lto
    ports:
      - 6869:6869
    environment:
      - LTO_NETWORK=TESTNET
      - ENABLE_REST_API=true
    networks:
      - lto

  indexer:
    container_name: indexer
    image: ltonetwork/indexer
    volumes:
      - lto-index:/usr/data/lto-index
    environment:
      - NODE_ENV=production
      - NODE_URL=http://public-node:6869
      - TRANSACTION_INDEXING=true
      - ASSOCIATION_INDEXING=all
      - IDENTITY_INDEXING=true
      - TRUST_NETWORK_INDEXING=true
      - 'TRUST_NETWORK_ROLES={"root": {"description": "The root role","issues": [{ "type": 100, "role": "university" }]},"university": {"description": "University"}}'
    ports:
      - 80:80
    networks:
      - lto
    depends_on:
      - public-node

volumes:
  lto-data:
  lto-index:

networks:
  lto:
    driver: bridge
