version: "2.4"

services:
  public-node:
    container_name: public-node
    image: ltonetwork/public-node:${LTO_NODE_VERSION:-latest}
    volumes:
      - lto-data:/lto
    environment:
      - LTO_NETWORK=${LTO_NETWORK:-MAINNET}
      - ENABLE_REST_API=true
    networks:
      - lto
    healthcheck:
      test: ["CMD-SHELL", "curl -s -f -L -o /dev/null http://localhost:6869/node/status"]
      interval: 30s
      timeout: 10s
      retries: 5

  indexer:
    container_name: indexer
    image: ltonetwork/indexer:${LTO_INDEXER_VERSION:-latest}
    volumes:
      - lto-index:/usr/data/lto-index
      - ./config:/etc/lto-index/      
    environment:
      - NODE_ENV=production
      - NODE_URL=http://public-node:6869
      - STORAGE_TYPE=${STORAGE_TYPE:-leveldb}      
      - LEVELDB_NAME=/usr/data/lto-index
      - REDIS_URL=${REDIS_URL:-redis://redis}      
      - IDENTITY_INDEXING=${DID_INDEXING:-true}
    ports:
      - ${PORT:-80}:80
    networks:
      - lto
    depends_on:
      public-node:
        condition: service_healthy

  redis:
    container_name: redis
    image: redis
    volumes:
      - lto-redis:/data
    networks:
      - lto
    profiles:
      - redis

volumes:
  lto-data:
  lto-index:
  lto-redis:

networks:
  lto:
    driver: bridge
